spring.application.name=passit
spring.datasource.url=jdbc:mysql://localhost:3307/passit?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=passit
spring.datasource.password=passit1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

mybatis.mapper-locations=classpath:/mapper/**/*.xml
mybatis.type-aliases-package=com.ssafy.passit
mybatis.configuration.map-underscore-to-camel-case=true

ai.server.url=http://127.0.0.1:8000
ai.system.author-id=1
ai.base-url=localhost:8000

spring.mvc.servlet.path=/api