spring.application.name=passit
spring.profiles.default=dev

mybatis.mapper-locations=classpath:/mapper/**/*.xml
mybatis.type-aliases-package=com.ssafy.passit
mybatis.configuration.map-underscore-to-camel-case=true
